@startuml Digital Credential States
hide empty description
top to bottom direction

' -- General diagram styling --
skinparam defaultFontSize 12
skinparam StateArrowColor black
skinparam StateArrowHeadSize 3
skinparam StateLineThickness 2

' -- Make corners and lines smoother --
skinparam roundCorner 20        ' larger corner radius
skinparam linetype polyline     ' use polyline routing

' -- Define states --
state AllStates as "All States"  {

state Suspended #FFA500
state Revoked #D64545
state Expired #D64545

' -- Transitions --


state IssuedOrValid as "Issued or Valid" {
  state Valid #008000

  [*] -right-> Issued : PID/(Q)EAA\nISS 
  Issued -right-> Valid : PID/(Q)EAA\nvalidity starts
}


IssuedOrValid -down-> Suspended : (Q)EAA\nSUSP
IssuedOrValid --> Revoked : PID/(Q)EAA\nREV 
IssuedOrValid --> Expired : PID/(Q)EAA\nEXP

Suspended -up-> IssuedOrValid : (Q)EAA\nUNSUSP
Suspended --> Revoked : (Q)EAA\nREV 
Suspended --> Expired : (Q)EAA\nEXP 

}


AllStates -down-> [*] : PID/(Q)EAA\nDEL
@enduml