@startuml Entities involved in Credential Revocation Flow
!include <C4/C4_Component>

HIDE_STEREOTYPE()

Person(user, "User", "Entity owning digital credentials")

Boundary(wallet_system, "Wallet System") {
    Component(wallet_instance, "Wallet Instance", "", "Manages user's Digital Credentials")
    Component(wallet_provider,"Wallet Provider", "", "Provides Wallet Instance and web services")
}

Component(authentic_source, "Authentic Source", "", "Provides User attributes to the Issuer and manages the validity status")
Component_Ext(authorized_body, "Authorized Entities", "", "SupervisoryBody, Judicial Authority, Identity Provider")

Component(issuer, "Credential Issuer", "", "Issues and manages Digital Credential and provides web services")

Component(digital_credential, "Digital Credential", "", "Contains attributes and validity status")


Rel(user, wallet_provider, "Revoke Wallet Instance")
Rel(user, wallet_instance, "Delete Credential")
Rel(user, issuer, "Revoke Digital Credential")

Rel(wallet_provider, wallet_instance, "Revoke Wallet Instances")
Rel(wallet_instance, issuer, "Notify Digital Credential deletion")
Rel(wallet_provider, issuer, "Notify Wallet Instance revocation")

Rel(authentic_source, issuer, "Notify attributes updates (values or validity status)")
Rel(authorized_body, issuer, "Notify Illegal Activities")

Rel(issuer,digital_credential, "Revoke/Suspend")
@enduml