@startuml Low-Level Presentation Phase
autonumber

    actor User as u
    
    participant "Wallet Unit" as w
    participant "RP Instance" as v

    u->w: Open the Wallet Instance
    activate w
    u<->w: User authentication by the Wallet Instance or by a WSCA

    u->w: User selects the proximity presentation functionality
    opt Mandatory if Step 2 is not performed by WSCA
    w<->u: User authentication by WSCA
    end
    w->w: Generate new ephemeral key pair \n(""EDeviceKey.Priv"", ""EDeviceKey.Pub"")
    w->v: Show the QR Code including ""DeviceEngagement""
    activate v
    v-->w: Scan the QR Code
    v->v: Generate new ephemeral key pair \n (""EReaderKey.Priv"", ""EReaderKey.Pub"")
    v->v: Compute session key
    
        
    v->v: Prepare a signed and encrypted attribute \nrequest (""SessionEstablishment"")
    v-->w: ""SessionEstablishment"" over BLE secure channel
    w->w: Compute session key
    w->w: Decrypt ""SessionEstablishment"" and verify its signature
    w-->u: Request approval for presenting selected attributes, \ncontents of registration certificate
    u->w: Approval
    w->v: Send a signed and encrypted response (""SessionData"") \nwith requested attributes over BLE secure channel
    v->v: Decrypt ""SessionData"", verify its signature \n(device binding) and check mdoc validity
    w<->v: Session Termination
    deactivate v
    deactivate w
@enduml