@startuml Low-Level Remote Protocol Flow
autonumber


Actor "User" as u

box "User's Devices" #LightBlue
participant "Wallet Instance" as w
participant "user-agent" as ua
end box

box "Relying Party" #LightBlue
participant "Relying Party\n(OAuth Client)" as ve
participant "status endpoint" as se
end box



activate u
u -> ua: Web Service navigation
activate ua
deactivate u
ua -> ve: Request Protected Resource

== Presentation Phase ==
activate ve
ve -> ve: Create a state value\nbound to user-agent cookie
ve -> ve: Create request_uri resource
ve -> ve: Inspect user-agent type\nto detect cross device or same device
ve -> ua: html page with QRCode or href containig the url with\nclient_id, request_uri, state, [request_uri_method]
deactivate ve


ua -> u: Show the QRCode page or click the href button
deactivate ua
activate w

group Cross Device only
w -> w: Scan QR Code
end

u --> w: Local User authentication

w -> w: Evaluate trust with the client_id

alt if request_uri_method is set with POST
    w -> ve: Provide Wallet metadata to the request_uri endpoint
    activate ve
    ve -> ve: Evaluate the Wallet tecnical capabilities
else if request_uri_method is set with GET or not present
   w -> ve: Request the signed request object from the request_uri endpoint
end

ve --> w: signed request object
deactivate ve


w -> w: Evaluate Relying Party Metadata and policies
w -> w: Verify signature of the signed Request Object
w -> w: Validate requested VP(s)
w -> u: Request for consent
activate u
u --> w: Confirmed
deactivate u
w -> ve: POST Authorization Response \n with vp_token, state, presentation_submission
activate ve
ve -> ve: Evaluate the Verifiable Presentation token
ve -> ve: Validate the Wallet Attestation. \nAttest the Wallet Provider\n is part of the Federation\n and the Wallet Instance is not revoked.
ve -> ve: Attest Credential Issuer Trust\n and Validate JWT Signature
ve -> ve: Process the credential

rnote over ve #LIGHTGREEN
Process the credential:
 - Check Holder Key Binding and Proof of Possession using  
   the public key bound in the Credential to verify the VP token.

 - Extract the disclosed attributes and check if all the required data are available.
endrnote

ve -> ve: Update the User session (cookie updated)


group Same Device with redirect_uri
ve --> w: HTTP/1.1 200 OK\n {"redirect_uri": https url with response_code }
w -> ua: Use the redirect_uri
activate ua
end

group Cross Device or Same Device without redirect_uri
ve --> w: HTTP/1.1 200 OK
deactivate w
deactivate ve
ua -> se:  JavaScript check: authentication state \n (HTTP request with cookie)
activate se
se --> ua: HTTP/1.1 200 OK\n {"redirect_uri": https url with response_code}

deactivate se

end


ua -> ve: Redirect to the protected resource
activate ve
ve --> ua: Protected resource

deactivate ua
deactivate ve
@enduml