@startuml IT-Wallet_System_Architecture_Ext
!include <C4/C4_Component>
HIDE_STEREOTYPE()
' skinparam linetype ortho
LAYOUT_LEFT_RIGHT()
' LAYOUT_TOP_DOWN()
' Define SPRITES
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/certificate>
!include <tupadr3/font-awesome-5/database>
!include <tupadr3/font-awesome-5/cogs>
!include <tupadr3/font-awesome-5/id_card>
!include <tupadr3/font-awesome-5/exchange_alt>
!include <tupadr3/font-awesome-5/wallet>
!include <tupadr3/font-awesome/institution>

' Custom styles
AddElementTag("external", $bgColor="#999999", $fontColor="white", $borderColor="grey")
AddElementTag("primary", $bgColor="#1168bd", $fontColor="white", $borderColor="#0b4884")
AddElementTag("tech", $bgColor="#6cb33f", $fontColor="white", $borderColor="#4a8329")
AddElementTag("governance", $bgColor="#8A398F", $fontColor="white", $borderColor="#55235A")

title IT-Wallet System Architecture - External Actors



' External Actors
Boundary(external, "External actors to IT-Wallet system", ""){
    Person(cie,"National Identity Provider", "National digital identity provider based on CIE (Electronic Identity Card).Provides strong authentication services and certified identity attributes for obtaining a PID and activating IT-Wallet Instance." ,$tags="external", $sprite="id_card")
    
    Component(pdnd,"","National Digital Data Platform (PDND)","National infrastructure for public data interoperability. Provides standardized APIs for accessing PA services, manages authentication and authorization between entities, implements security patterns and shared data governance.", $tags="external",$sprite="exchange_alt")

    Component(auth_third_parties, "Authorized Third Parties", "Judicial or Supervisory Bodies and Legal Authorities", "Law enforcement agencies, judicial authorities, regulatory bodies authorized by law to access specific IT-Wallet data for legal proceedings,investigations or regulatory compliance.", $tags="external", $sprite="institution")

    Lay_U(cie,pdnd)
    Lay_U(pdnd,auth_third_parties)
}


@enduml