@startuml Re-Issuance Flow Diagram
!include <C4/C4_Dynamic>


start
note right
When a Digital Credential needs to be updated, the Credential Issuers MAY send a notification to the User using a registered out-of-band communication channel.
end note

:User opens Wallet Instance;

if (Revocation mechanism \n = Status List ?) then (yes)
 
   :Retrieve Status List Token for
    stored Credentials;
    note left
    Required when no valid
    Status List Token exists
    end note
    if (Credential Status in [0x03, 0x04]?) then (yes)
     else (no) 
             stop
     endif
    else (no)

    :Retrieve Status Assertions for
    stored Credentials;
    note right
    Required when no valid
    Status Assertions exists
    end note

    if (Credential Status = INVALID?) then (yes)
        if (credential_status_detail.state in
        [UPDATE, ATTRIBUTE_UPDATE]?) then (yes)
        else (no) 
             stop
        endif
     else (no) 
             stop
     endif
endif

        if (Access Token valid?) then (yes)
            
        else (no)
            if (Refresh Token valid?) then (yes)
              :Start Refresh Token Flow;
            else (no)
              stop
              note 
               Start an new Issuance flow
               with User's Authentication 
              end note
            endif
        endif
        
        :Use DPoP Access Token to retrieve
        new Digital Credential;
        if (Credential status = 0x04, or \ncredential_status_detail.state = ATTRIBUTE_UPDATE?) then (yes)
            :Request User Authorization;            
            if (User Authorizes?) then (yes)
                :Store new Credential;
            else (no)
                stop
            endif
        else (no)
            :Store new Credential;
        endif

        :Delete previous Credential;

stop
@enduml