@startuml Digital Credential Catalogue Entities
!include <C4/C4_Component>

' Define SPRITES
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/certificate>
!include <tupadr3/font-awesome-5/database>
!include <tupadr3/font-awesome-5/lock>
!include <tupadr3/font-awesome-5/users>
!include <tupadr3/font-awesome-5/cogs>
!include <tupadr3/font-awesome-5/server>
!include <tupadr3/font-awesome-5/key>
!include <tupadr3/font-awesome-5/user>
!include <tupadr3/font-awesome-5/id_card>
!include <tupadr3/font-awesome-5/exchange_alt>
!include <tupadr3/font-awesome-5/desktop>
!include <tupadr3/font-awesome-5/wallet>
!include <tupadr3/font-awesome/institution>


Component(catalogue, "Digital Credentials Catalogue", "Registry", "Central registry of all available Digital Credentials", $sprite="database")


Person(user, "User", "Citizens who discover and request Digital Credentials", $sprite="user")
Component(trustAnchor, "Trust Anchor", "", "Manages and maintains the Digital Credential Catalogue", $sprite="key")
System(supervisoryBody, "Supervisory Body", "Monitors registration phase ensuring security and privacy", $sprite="certificate")
System(issuers, "Digital Credential Issuers", "Authorized entities that issue Digital Credentials", $sprite="id_card")
System(relyingParties, "Relying Parties", "Use the catalogue to gather information about credentials", $sprite="exchange_alt")
System(walletProviders, "Wallet Providers", "Access the catalogue to integrate credentials into wallets", $sprite="wallet")
System(authenticSources, "Authentic Sources", "Hold original data attested in Digital Credentials", $sprite="institution")

Rel(trustAnchor, catalogue, "Manages, maintains and publishes", "Federation endpoint")
Rel(supervisoryBody, trustAnchor, "Interacts with")
Rel(supervisoryBody, catalogue, "Monitors registration process")
Rel(issuers, catalogue, "Register Digital Credentials in")
Rel(authenticSources, issuers, "Interacts with")
Rel(relyingParties, catalogue, "Gather information about Digital Credentials")
Rel(walletProviders, catalogue, "Access to identify available credentials")
Rel(user, walletProviders, "Uses Wallet Instance provided by")
Rel_D(user, catalogue, "Indirectly discovers and requests credentials")
@enduml