@startuml Credential Request Flow by the User
autonumber 1.1

participant "User" as u

box "User's smartphone" #LightBlue
participant "Browser" as br
participant "Wallet Instance" as w
end box

box "User's external device" #Orange
participant "Browser" as bre
end box

participant "Credential Issuer" as i

alt if Wallet Initiated Flow

u -> w: Open the Wallet Instance app\nlocal user authentication
activate w
w -> u: obtain your Digital Credential
u --> w: yes

rnote over w #WHITE
Obtain the list of the Trusted Credential Issuers
endrnote

w->u: confirm the selection of Credential Issuer

u-->w: ok

deactivate w

else if Issuer Initiated Flow

autonumber 2.1

u -> i: Open PID/(Q)/EAA Provider website
i -> u: obtain your Digital Credential
u --> i: yes

alt if Cross Device Flow

i -> bre: html page with QRCode containing Credential Offer
bre -> u: Show the QRCode page
u --> w: Open the Wallet Instance app\nlocal user authentication
activate w
w -> w: Scan QR Code



else if Same Device Flow

i -> br: html page with href containing Credential Offer
br -> u: click the href button


u --> w: Open the Wallet Instance app\nlocal user authentication
activate w

end

end
@enduml