@startuml High Level Remote Protocol Flow
participant "Wallet Instance" as w
participant "Relying Party" as rp

rp -> w: 1. **Authorization Request** (w request_uri) through redirect or QR code scan \nto the //Wallet's Authorization Endpoint//

w -> rp: 2. **Request URI Request** (GET or POST) to the //RP's Request URI Endpoint//

rp -> w: 3. **Request URI Response** (w Request Object)

w -> w: 4. **WI Checks** 

w -> w: 5. **User Consent** 

w -> rp: 6. **POST Authorization Response** (w vp_token) to the //RP's Response URI Endpoint//

rp -> rp: 7. **RP Checks** 

rp -> w: 8. **Relying Party Response** (optionally w redirect_uri)
@enduml